### ISSUE TITLE
can't install version 1.1.6 , 1.1.5 on python 2.7 . Is it supported ?

### ISSUE THREAD

**Issue by kargotools** [wialon/python-wialon#14]
pleasee help, getting the following error.
   
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-QyZdg1/python-wialon/setup.py'"'"'; __file__='"'"'/tmp/pip-install-QyZdg1/python-wialon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zJvwt7
         cwd: /tmp/pip-install-QyZdg1/python-wialon/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-QyZdg1/python-wialon/setup.py", line 3, in <module>
        import wialon
      File "wialon/__init__.py", line 6, in <module>
        from .api import Wialon, WialonError
      File "wialon/api.py", line 3, in <module>
        from builtins import str
    ImportError: No module named builtins
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Mixser** [comment]
Hi @kargotools 

Thanks for issue, we have fixed it in `1.1.7`, you can install right now by executing
```
pip2 install python-wialon --no-cache-dir
```
