### ISSUE TITLE
TypeError: call() got multiple values for argument 'action'

### ISSUE THREAD

**Issue by maxim-bu** [wialon/python-wialon#16]
Hello,
First of all, I will give an example where the raise exception:

```
from wialon import Wialon
w_api = Wialon(token='...')
w_api.report_exec_report(...)
w_api.report_get_result_chart(attachmentIndex=0, **action**=0, width=800, height=600, autoScaleY=1, pixelFrom=15, pixelTo=750, 
flags=0x1)
```

Have exception:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/maxim/.local/lib/python3.8/site-packages/wialon/api.py", line 211, in get
    return self.call(action_name, *args, **kwargs)
TypeError: call() got multiple values for argument 'action'
```

Method **report_get_result_chart** have argument **action** (https://sdk.wialon.com/wiki/en/kit/remoteapi/apiref/report/get_result_chart)
But method **Wialon.call** also have argument **action**. Any API method call method **Wialon.call**, so we have name conflict.

I think the solution to the problem is: rename **Wialon.call** argument **action** to **action_** or **action_name**

Thank you for the attention

**Comment by Lenka42** [comment]
Hi @maxim-bu 
I changed argument name to `action_name` in methods `request` and `call`. Please upgrade library version to `1.2.1` and let me know if this solves your problem.

**Comment by maxim-bu** [comment]
Hi, @Lenka42 
Problem is solved, thank you

**Comment by Lenka42** [comment]
@maxim-bu thanks for feedback!
