### ISSUE TITLE
[question] How can i get demo access to wialon

### ISSUE THREAD

**Issue by o-murphy** [wialon/python-wialon#26]
Before I pleced there MR with [async implementation of wialon api client](https://github.com/o-murphy/py-aiowialon)
I used to have access to the Wialon Local server where I could test the library, but now I don't
How can I get Demo access to Wialon to continue work with the library?

**Comment by ashmigelski** [comment]
You can find demo creds on [Wialon Playground](https://sdk.wialon.com/playground/demo/login) page
