### ISSUE TITLE
Wrapper installation crashes

### ISSUE THREAD

**Issue by infragmt** [wialon/python-wialon#5]
Hi!
I had a problem installing this module. I´m running Python 3.5.2 x64 on a Windows 10 Pro box.
Most likely I'm doing something wrong but I can't find the issue.
I tried to install it through pip install python-wialon but I've got the same error.

C:\Users\user\Desktop\python-wialon-1.1.0>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import wialon
  File "C:\Users\user\Desktop\python-wialon-1.1.0\wialon\__init__.py", line 4, in <module>
    import flags
ImportError: No module named 'flags'

Thanks for your time and sorry for the inconvenience.

**Comment by wialon** [comment]
Hello,


All consultations with our developers are available on forum.gurtam.com
Please, post your issue on forum in SDK branch and kindly wait for the reply from the developers.

On Wed, 26 Oct 2016, reply@reply.github.com wrote:
> Hi!
> I had a problem installing this module. I´m running Python 3.5.2 x64 on a
> Windows 10 Pro box. Most likely I'm doing something wrong but I can't find
> the issue. I tried to install it through pip install python-wialon but
> I've got the same error.
>
> C:\Users\user\Desktop\python-wialon-1.1.0>python setup.py install
> Traceback (most recent call last):
>   File "setup.py", line 3, in <module>
>     import wialon
>   File "C:\Users\user\Desktop\python-wialon-1.1.0\wialon\__init__.py",
> line 4, in <module>     import flags
> ImportError: No module named 'flags'
>
> Thanks for your time and sorry for the inconvenience.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/wialon/python-wialon/issues/5



Best regards,

Sergey Novikov
Technical Support Department
Gurtam


tel: +370 37 999 460
tel: +7 4999 183 186


Please rate how good we helped you in this ticket:
https://support.gurtam.com/gurtam_rating/PLE-64869-271

**Comment by infragmt** [comment]
Hello
Thank you for the prompt answer.
I've switched to Linux and it started working.
All my future inquiries will be channeled through Gurtam forum.
Best regards.

> Hello,
> All consultations with our developers are available on forum.gurtam.com
> Please, post your issue on forum in SDK branch and kindly wait for the reply from the developers.
> 
> Best regards,
> 
> Sergey Novikov
> Technical Support Department
> Gurtam
> tel: +370 37 999 460
> tel: +7 4999 183 186
