### ISSUE TITLE
pip install python-wialon gives "ImportError: No module named 'flags'"

### ISSUE THREAD

**Issue by sagapeak** [wialon/python-wialon#6]
Hi, 

I'm using Python 3.5.2. When I ran ``pip install python-wialon`` I received the following error:

```
$ pip install python-wialon
Collecting python-wialon
  Downloading python-wialon-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v0/phxxyfwd5p5gkzt466v9qjrh0000gn/T/pip-build-n0ouxwll/python-wialon/setup.py", line 3, in <module>
        import wialon
      File "/private/var/folders/v0/phxxyfwd5p5gkzt466v9qjrh0000gn/T/pip-build-n0ouxwll/python-wialon/wialon/__init__.py", line 4, in <module>
        import flags
    ImportError: No module named 'flags'

```

It seems like ``py-flags`` is a dependency. After I installed ``py-flags``, the install for python-wialon worked. 

Maybe py-flags can be added to setup.py?

thanks!

**Comment by sagapeak** [comment]
After digging into the code, I realised that you don't intend to use ``py-flags``. Rather, you want to use the flags.py in the wialon folder. 

In wialon/__init__.py, do this instead for explicit relative imports:

```
from . import flags
```

**Comment by ashmigelski** [comment]
@sagapeak Thanks for reporting :+1: 

I changed import in `wialon/__init__.py` as you recommended
`pip install python-wialon` now works correctly (tested for Python 3.5.2 and Python 2.7.6)

**Comment by sagapeak** [comment]
Welcome!
